### ISSUE TITLE
Not seeing raw data

### ISSUE THREAD

**Issue by LFGaming** [smartlockpicking/BLE_HackMe#2]
It seems `nRF Connect` does not have the option to show raw data anymore like before and like the explenation in the program, this makes it (for me atleast) impossible to go further than `3) BLE Advertisements`, am I doing something wrong? 
This is for Ios, no idea for android at this moment.

**Comment by smartlockpicking** [comment]
Unfortunately nRF Connect for iOS has less features than for Android. This is among others due to the restrictions imposed by Apple's OS. The HackMe is designed for Android version of nRF Connect, as pointed out in "Requirements" section of [description](https://smartlockpicking.com/ble_hackme/). You may still be able to solve some of the tasks using iPhone, but you will soon most likely encounter also other issues - for example lack of "macros" functionality.

If you don't have Android phone, another possibility is to use other BLE tools, running for example on Linux or Mac system. Details however are not covered in the HackMe instructions. For scanning raw BLE advertisement packets in Linux command line, you can start for example with `hcitool lescan` or `scan on` in `bluetoothctl` and at the same time `hcidump` or `btmon` with proper parameters to see the incoming packets in console or dump to btsnoop readable by Wireshark.

**Comment by LFGaming** [comment]
Ah okay, my fault for not reading correctely,, wil find something to still use the app. Thanks for the quick respose :)
